"""
models.py
---------
Dataclass definitions for the corporate_chunks storage layer.
Mirrors the design of metadata_manager/models.py but adapted for
CorporateChunker output (LLM-refined text + document metadata context).
"""

from dataclasses import dataclass, field
from typing import Optional, List


@dataclass
class CorporateChunkInput:
    """
    The data structure passed INTO the store from the ChunkOrchestrator.
    Represents one LLM-refined chunk ready for persistence.
    """
    doc_id:      str            # Linked document ID (e.g., "2016_580ab4")
    chunk_index: int            # Position within the document
    content:     str            # LLM-refined text from CorporateChunker
    chunk_hash:  str            # SHA-256 of the refined content (deduplication key)
    metadata:    dict           # Full document metadata JSON context (category, title, etc.)
    embedding:   Optional[List[float]] = None  # Nullable — populated in a separate process


@dataclass
class StoredCorporateChunk:
    """
    Represents a fully stored corporate_chunk record — what comes OUT of the DB.
    Includes all CorporateChunkInput fields plus auto-generated storage fields.
    """
    # --- Identity (auto-generated by DB) ---
    id:          Optional[int]  # AUTOINCREMENT primary key

    # --- Link to source document ---
    doc_id:      str
    chunk_index: int

    # --- Content ---
    content:     str            # LLM-refined text
    chunk_hash:  str            # Deduplication hash

    # --- Metadata Context ---
    metadata:    Optional[str]  # Stored as JSON string in SQLite

    # --- Embedding (populated later) ---
    embedding:   Optional[str]  # Stored as JSON string array, nullable

    # --- Audit Fields ---
    created_at:  str            # ISO UTC timestamp of insertion


@dataclass
class ChunkStorageResult:
    """
    Returned by every public method in CorporateChunkStore.
    Lets callers check success/failure without catching exceptions.
    Mirrors the StorageResult pattern from metadata_manager.
    """
    success: bool
    message: str
    data: Optional[object] = None   # StoredCorporateChunk, list, or None


@dataclass
class ChunkBatchResult:
    """Result of a bulk insert operation."""
    total_count:    int
    inserted_count: int
    skipped_count:  int
    failed_count:   int
    errors: list = field(default_factory=list)
